### ISSUE TITLE
several undeclared dependencies in functions

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#114]
enforce consistent use of `::` to declare dependency to imported functions

**Comment by tomaszaba** [comment]
@ernestguevarra, just to remind you that dependencies were not explicitly declared in the code, using `package::function`, simply because the approach used/adopted was to declare in the `NAMESPACE` file with `usethis::import_from("package_name", "function_name").` This writes `importFrom(package, function)` in `NAMESPACE`.
